# Generated by Django 5.1.4 on 2025-01-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0165_grant_prometheus_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="last_org",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgs.org"),
        ),
    ]
