# Generated by Django 5.1.4 on 2025-02-12 17:00

from django.db import migrations

from temba.utils.uuid import uuid4


def populate_channel_events_uuid(apps, schema_editor):
    ChannelEvent = apps.get_model("channels", "ChannelEvent")

    num_updated = 0
    for event in ChannelEvent.objects.all():
        if not event.uuid:
            event.uuid = uuid4()
            event.save(update_fields=("uuid",))

            num_updated += 1

    if num_updated:
        print(f"Updated {num_updated} channel events")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    populate_channel_events_uuid(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0189_channelevent_uuid_alter_channelevent_event_type"),
    ]

    operations = [
        migrations.RunPython(populate_channel_events_uuid, migrations.RunPython.noop),
    ]
