# Generated by Django 5.1.4 on 2025-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0282_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="is_android",
            field=models.BooleanField(),
        ),
    ]
