# Generated by Django 5.1.4 on 2025-01-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0360_alter_flowsession_modified_on"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flowsession",
            name="flows_session_waiting_has_started_and_expires",
        ),
    ]
