# Generated by Django 5.1.4 on 2025-01-06 21:25

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):

    dependencies = []

    operations = [InstallSQL("0007_functions"), InstallSQL("0007_triggers")]
